# 文章封面图片
post_image:

# 欢迎图片
welcome_image:

# 欢迎标语
welcome_title:

# Favicon
favicon:

# 网站关键字
keywords:

# 版权信息
copyright:

# 插件
fancybox:
pjax:

# CDN
vendors:
  query_js:
  fancybox_js:
  pjax_js:
  fancybox_css: